### ISSUE TITLE
 No such file or directory: './results/FMA-Net\\test\\avg_rgb_psnr.txt'

### ISSUE THREAD

**Issue by 17307181179** [KAIST-VICLab/FMA-Net#22]
when I run the main.py by "python main.py --test --config_path experiment.cfg",This question arises，How can i get the text，thank you

**Comment by 17307181179** [comment]
'TestReport' object has no attribute 'total_rgb_psnr_logFile' and this

**Comment by GeunhyukYouk** [comment]
Hi, sorry for the late reply. 

This issue is likely due to an incorrect path setting in the [test_quantitative_result](https://github.com/KAIST-VICLab/FMA-Net/blob/337bb45f56b1e550073eaa0dfaee199395a3606f/main.py#L57) function. Make sure the `gt_dir` and `output_dir` paths are correct and try again.
